### ISSUE TITLE
How to deploy to Github pages?

### ISSUE THREAD

**Issue by myrtleTree33** [slara/generator-reveal#50]
I'm trying to push to github pages, but it is giving this error:

```
Running "buildcontrol:pages" (buildcontrol) task

Creating branch "gh-pages".
Warning: fatal: Failed to resolve 'HEAD' as a valid ref.
 Used --force, continuing.
Warning: Task "buildcontrol:pages" failed. Used --force, continuing.

Done, but with warnings.
```

I've tried creating a `HEAD` as suggested in http://stackoverflow.com/questions/4848607/git-fatal-no-such-ref-head - but it doesn't seem to solve it.

**Comment by prashcr** [comment]
I don't quite understand how the deploy works either :disappointed: 

Right after generating, when I try to upload to an empty repo, it says
```
Running "buildcontrol:pages" (buildcontrol) task
Warning: There are uncommitted changes in your working directory.
Please commit changes to the main project before you commit to
the built code.
 Use --force to continue.

Aborted due to warnings.
```

So I tried adding and commit the whole folder.

After that, `deploy` works and it seems to create a new repo in the `dist` directory and it pushes just that to the gh-pages branch. However, this gh-pages branch is missing all the `bower_components`, so the gh pages site is nothing but a bunch of 404s. 

Would it be possible to provide an example of a deploy workflow? I don't understand why it needs to create a seperate git repo in `dist` but also require the main directory to be under its own repo. I assumed `grunt dist` would build all the files for `dist`, why does `dist` still require `bower_components`?

**Comment by prashcr** [comment]
Hmm, so the separate git repo for the `dist` dir is a `grunt-build-control` feature, I see.

I just don't understand why `dist` dir requires `bower_components`. The deploy works fine if I manually `git add -f bower_components`, but yeah...is this a bug? I was expecting to see one big css and one big js file in dist, but that doesn't seem to be happening

**Comment by janraasch** [comment]
Try using `grunt deploy`. This should take care of copying assets like `bower_components` to the right place before running the `buildcontrol` task. Let me know if that helps.

**Comment by prashcr** [comment]
That's what I tried actually.
##### Steps taken
```
yo reveal
```
- With all default options except for adding a GH repo (Y)
- Initialize git repo, add all, initial commit (otherwise `grunt deploy` fails)
```
grunt deploy
```
Output
```
test git:(master) grunt deploy
Running "coffeelint:all" (coffeelint) task
>> 1 file lint free.

Running "jshint:all" (jshint) task
>> 1 file lint free.

Running "buildIndex" task

Running "copy:dist" (copy) task
Created 34 directories, copied 174 files

Running "buildcontrol:pages" (buildcontrol) task

Creating git repository in "dist".
Initialized empty Git repository in /Users/prashanthcr/Programming/angular-testing/test/dist/.git/

Creating remote.

Creating branch "gh-pages".
Switched to a new branch 'gh-pages'

Committing changes to "gh-pages".
[gh-pages (root-commit) 9f01092] Built from 166f79a on branch master
 4 files changed, 139 insertions(+)
 create mode 100644 index.html
 create mode 100644 js/loadhtmlslides.js
 create mode 100644 slides/index.md
 create mode 100644 slides/list.json

Pushing gh-pages to git@github.com:prashcr/reveal-test.git
To git@github.com:prashcr/reveal-test.git
 * [new branch]      gh-pages -> gh-pages

Done, without errors.
```
Result: https://github.com/prashcr/reveal-test

**Comment by janraasch** [comment]
Could you try to append the line 

`!dist/bower_components`

to the end of the generated `.gitignore` file?

**Comment by janraasch** [comment]
Could you make sure that your not gitignoring `bower_components` globally also?

**Comment by prashcr** [comment]
Yeah, I am gitignoring `bower_components` globally, since that seems to be the convention everywhere.

Serving the whole `bower_components` folder unminified isn't very economical though is it?
Why not concatenate and minify the CSS and JS?

**Comment by janraasch** [comment]
Sure, you are absolutely right. Minifying would be great, but then again, the markdown and html slide integration works by synchronously loading the files *when needed*. So really, if you care about performance. you should bundle this all up into a single html file and minify that. Then again that seems like an awful lot of trouble for the use case (of being able to quickly throw together some slides for a presentation).

**Comment by prashcr** [comment]
On another note, I wanted to ask about the git functionality of `grunt deploy`. Right now, it requires 2 git repos, one for the src, and another for the built code. Ideally, it would be much simpler to use one repo, and deploy to a branch on that same repo. I took a look at `grunt-build-control` and it seems like this should be easily supported.

What's really puzzling though, is that I came across this guide from last year on getting started with reveal.js, along with this generator: http://slidedeck.io/RiaanBurger/slides-revealjs  
And in the guide it mentions that `grunt deploy` pushes to a different branch on the same repo.
Why and when did that change?

**Comment by janraasch** [comment]
The repo should be the one you specified when first generating the project. It is reflected in the task configuration of the `buildcontrol` task in your generated `Gruntfile.coffee`:

```coffee
...
pages:
  options:
    remote: 'git@github.com:.....'
...
```

**Comment by prashcr** [comment]
Ah, my bad. I confuddled myself over the fact that there are two local repos but only one remote repo, and I was forgetting to push the main repo before instead of after calling `grunt deploy`.  
Thanks!

**Comment by janraasch** [comment]
Sure, no problem.
