### ISSUE TITLE
Allow reveal:slide to create slide in a subdirectory

### ISSUE THREAD

**Issue by dvberkel** [slara/generator-reveal#62]
I would like to structure my presentations in such a way that slides that form a short narrative go in a different directory. E.g. the introduction slides go into a directory `slides/introduction` while the conclusions go into a directory `slides/conclusion`.

At the moment the [`reveal:slide`][reveal:slide] command does not allow this option.

I propose to enhance the command with a new option `--directory` that would indicate in which sub-directory the generated slide should go. It should make the directory if it does not exist yet, but only if it is a directory below `slides`.

If this is a desirable feature, then I will provide a pull-request.

[reveal:slide]: https://github.com/slara/generator-reveal/blob/v0.4.0/slide/index.coffee

**Comment by janraasch** [comment]
No action, since half a year. Thus I am closing this.
