### ISSUE TITLE
Update to support reveal.js 3.x

### ISSUE THREAD

**Issue by Delapouite** [slara/generator-reveal#63]
Hello

A new skin (black) has been introduced in this new version of reveal. Are there any other improvements or breaking changes that need to be supported?

**Comment by janraasch** [comment]
I think the update will be quiet easy for us. Hoping to have this done by the end of t he week.

**Comment by janraasch** [comment]
Fixed with 8423234703d142c9ef24660ec5cdda6b7b117f44.
