### ISSUE TITLE
reduce upload size

### ISSUE THREAD

**Issue by EdoPut** [slara/generator-reveal#66]
[Copying everything inside bower_componentes](https://github.com/slara/generator-reveal/blob/master/app/templates/_Gruntfile.coffee#L80) result in copying ~~160mb~~ 3mb from reveal.js directory. (160 if your reveal.js is customised and linked locally with bower)

Maybe [bower-wiredep](https://github.com/stephenplusplus/grunt-wiredep) and [grunt-bower](https://www.npmjs.com/package/grunt-bower) can save the day.

**Comment by janraasch** [comment]
`3mb` does not seem that bad right?

**Comment by EdoPut** [comment]
Yeah it's true, it's not bad but copying everything in a new project adds:

- 600kB of highlight themes that mostly I don't need, we can use a single theme after all
- 300kB of js tests
- 90kB of unminized  code
- 112kB from Sass sourcecode

basically you could skim the size of a fresh project with __only__ reveal.js and reveal-highlight by a third

**Comment by janraasch** [comment]
No action, since two months. Thus I am closing this.
