### ISSUE TITLE
Markdown slides separation

### ISSUE THREAD

**Issue by dangior** [slara/generator-reveal#70]
Hi, first of all thanks for the contribution, it works great! Just one question, how do I do for separate slides horizontal and vertically under the same Markdown file?

Regards,

**Comment by janraasch** [comment]
Hi @dangior. This is really more of a general [reveal.js](https://github.com/hakimel/reveal.js) question, so please refer to the [reveal.js](https://github.com/hakimel/reveal.js) README.md for more details. The gist is: 

There are data attributes `data-separator` and `data-separator-vertical` which you may specify to control the parsing behavior of a given markdown slide.

If you do not explicitly specify these attributes on a slide, only horizontal separation works, with a value of `^\n---\n`, so e.g.

```markdown
first slide

---

next slide (horizontal)
```

But you can set those attributes to anything you like by putting the declaration into the `slides/list.json` file. So you could have a `list.json` with content

```json
[{
        "filename": "slide-title.md",
        "attr": {
            "data-separator": "^\n---\n",
            "data-separator-vertical" : "\n--\n"
        }
}]
```

(the generator will give you a good starting point by running `yo reveal:slide "Slide Title" --markdown --attributes`) and then in your `slides/slide-title.md` file you might have

```markdown
first slide

---

next slide (horizontal)

--

next slide (vertical)
```

Hope that helps...

**Comment by dangior** [comment]
Hi Jan, it works like a charm! for me is more useful to have several slides included in the same file so it will help a lot.

Thanks a lot!
