### ISSUE TITLE
Feature: git add + git commit new slide as it is created 

### ISSUE THREAD

**Issue by amjames** [slara/generator-reveal#77]
I think it would be very useful/handy to add an option to have the generator run `git-add` and or `git-commit` when creating new slides.  

### Pros
I find I forget quite often to add a new slide to the index, and forget to commit changes in `slides/list.json` (since I hardly every edit it by hand).  

### Cons
Have a generic "added slide .." commit message scattered throughout the history would not be pretty, but in my opinion is very useful for searching the history. I really like having them in there for each slide, others may disagree. 

### Thoughts on implementation
Could be decided at setup when you pick the theme in that case being an always or never event. Or just a per invocation flag, *eg* `yo reveal:slide mynewslide --git` would: 

1. create `slides/mynewslide.html`
2. modify `slides/list.json`
3. `git add slides/list.json slides/mynewslide.html` 
4. ? `git commit -m " created  mynewslide"`

The 4th point should probably optional. It is possible you don't want commits to be made automatically for you.

**Comment by janraasch** [comment]
Hi @amjames, sounds like a neat idea. I would prefer the `yo reveal:slide mynewslide --git`-like approach. We should keep this optional (first?/for now?) as only usage by more than a few users will show how something like this might yield unwanted results (e.g. when my `git-status` is not clean before running the command anyway.)

1. One question about the feature. Would you really want to run `git commit -m " created mynewslide"` or rather `git commit -am " created mynewslide"`?

2. And a related question, if (3.) of your implementation idea is really want you eases your pain, then let's just do that straight away and see where to go next, once we have that in place. Maybe we do not even need to think about (4.).

**Comment by amjames** [comment]
To answer those points: 

1. In my original idea I actually intended to separate `git add` and `git commit`. If the working branch already has uncommitted changes in the index, or there are tracked files then `git add` is still safe.  It is not very difficult to undo/work around. 

2. I completely agree my (3.) is much less trouble, and would be great start. If this ends up being useful then perhaps (4.) could be introduced in some way. 

Some thoughts of mine: 

It would be fairly easy (thanks to `git status --porcelain`) to check if any of these git commands would be unsafe it issue. The `--git` flag could be ignored (with warning in the output) if there are uncommitted changes, un-tracked files, unresolved conflicts, or any combinations.  

*If* the auto-merge feature was something that got interest I think that the best way to do it would be to have the user specify/select a "commit-title-string-template" that will be the start of an auto-generated commit message. Then when the slide is created there would be a separate flags for `git add` vs `git add `+ `git commit`. And the commit would look like this:  

`git commit -m "<commit-title-string-template (with any replacements done)>" -e`

That would open a commit message in `$EDITOR` with some part of a message in place. The final commit would aborted if that file is not written.

**Comment by janraasch** [comment]
Sounds good. I would definitely be open to add a flag for `git add`, à la

```bash
yo reveal:slide mynewslide --git-add
```

Can you submit a pr with the implementation and a test case?

**Comment by amjames** [comment]
Sorry for the delay,  I will submit a PR when I get a working implementation, and set up a test case. I have been hacking away at it, but I am also trying to finish up a rather important presentation for Tuesday.  

I will probably be able to submit a pr sometime after that.

**Comment by janraasch** [comment]
Sure, no worries. Good luck with your presentation, @amjames. :)

**Comment by janraasch** [comment]
No action on this, since two month. I am closing this.
