### ISSUE TITLE
pause on slide transition with opacity on background image

### ISSUE THREAD

**Issue by bdarcus** [slara/generator-reveal#80]
Am not exactly sure how to describe this, or understand what's going on, but ...

If I have a presentation, where a slide has a background image with the opacity set, there's a pause where one can see the image of the preceding slide.

Anything you (or I) can do to shorten that so it's not a distraction?

**Comment by janraasch** [comment]
Can you provide a small sample presentation which has the issue you described?

**Comment by bdarcus** [comment]
Sorry I've been slow getting back to this. Two things:

1) I don't have the sample anymore, but behavior is apparent if you have
more than one slide background image with opacity set. But ....

2) I don't really think it matters in retrospect, because there are better
ways the get result I wanted.
